"""Type stub for ``aero1553._native``, the compiled PyO3 extension.

Built from ``python/native/src/``. Keep this file in step with the
``#[pyclass]`` / ``#[pyfunction]`` / ``m.add`` items there: mypy trusts it,
and nothing else checks it against the binary.
"""

from collections.abc import Iterable, Iterator, Sequence
from os import PathLike
from pathlib import Path
from typing import Any, TextIO, final

from aero1553.models import Bus, Direction, MessageFormat, TimeRender

__version__: str
TERMINATOR_TYPE_WORD: int

# Run the aero1553 command line; argv[0] is the program name. Returns the
# L2-CLI-011 exit status.
def run_cli(argv: list[str]) -> int: ...

@final
class TypeWord:
    def __init__(
        self, message_type: int, bus: int, word_count: int, error: bool, raw: int
    ) -> None: ...
    @property
    def message_type(self) -> int: ...
    @property
    def bus(self) -> Bus: ...
    @property
    def word_count(self) -> int: ...
    @property
    def error(self) -> bool: ...
    @property
    def raw(self) -> int: ...
    def __replace__(self, **changes: Any) -> TypeWord: ...
    def __hash__(self) -> int: ...

@final
class CommandWord:
    def __init__(
        self, rt: int, direction: int, subaddress: int, data_word_count: int, raw: int
    ) -> None: ...
    @property
    def rt(self) -> int: ...
    @property
    def direction(self) -> Direction: ...
    @property
    def subaddress(self) -> int: ...
    @property
    def data_word_count(self) -> int: ...
    @property
    def raw(self) -> int: ...
    @property
    def is_broadcast(self) -> bool: ...
    @property
    def is_mode_code(self) -> bool: ...
    def __replace__(self, **changes: Any) -> CommandWord: ...
    def __hash__(self) -> int: ...

@final
class IrigTimestamp:
    def __init__(
        self, day: int, hour: int, minute: int, second: int, microsecond: int, freerun: bool
    ) -> None: ...
    @property
    def day(self) -> int: ...
    @property
    def hour(self) -> int: ...
    @property
    def minute(self) -> int: ...
    @property
    def second(self) -> int: ...
    @property
    def microsecond(self) -> int: ...
    @property
    def freerun(self) -> bool: ...
    def to_total_microseconds(self) -> int: ...
    def to_microseconds(self, _standard_tick_rate_hz: float | None = None) -> int | None: ...
    def format(self) -> str: ...
    def format_with(self, render: TimeRender) -> str: ...
    def __replace__(self, **changes: Any) -> IrigTimestamp: ...
    def __hash__(self) -> int: ...

@final
class StandardTimestamp:
    def __init__(self, raw_value: int, upper_word: int, lower_word: int) -> None: ...
    @property
    def raw_value(self) -> int: ...
    @property
    def upper_word(self) -> int: ...
    @property
    def lower_word(self) -> int: ...
    def raw_ticks(self) -> int: ...
    def to_microseconds(self, standard_tick_rate_hz: float | None = None) -> int | None: ...
    def format(self) -> str: ...
    def format_with(self, render: TimeRender) -> str: ...
    def __replace__(self, **changes: Any) -> StandardTimestamp: ...
    def __hash__(self) -> int: ...

@final
class MieMessage:
    def __init__(
        self,
        timestamp: IrigTimestamp | StandardTimestamp,
        type_word: TypeWord,
        message_format: int,
        command_word: CommandWord | None,
        command_word_2: CommandWord | None,
        status_word: int | None,
        status_word_2: int | None,
        data_words: tuple[int, ...] | list[int],
        error_word: int | None,
        delta: float | None,
        file_offset: int,
        mux: str | None = None,
    ) -> None: ...
    @property
    def timestamp(self) -> IrigTimestamp | StandardTimestamp: ...
    @property
    def type_word(self) -> TypeWord: ...
    @property
    def message_format(self) -> MessageFormat: ...
    @property
    def command_word(self) -> CommandWord | None: ...
    @property
    def command_word_2(self) -> CommandWord | None: ...
    @property
    def status_word(self) -> int | None: ...
    @property
    def status_word_2(self) -> int | None: ...
    @property
    def data_words(self) -> tuple[int, ...]: ...
    @property
    def error_word(self) -> int | None: ...
    @property
    def delta(self) -> float | None: ...
    @property
    def file_offset(self) -> int: ...
    @property
    def mux(self) -> str | None: ...
    @property
    def rt(self) -> int | None: ...
    @property
    def subaddress(self) -> int | None: ...
    @property
    def bus(self) -> Bus: ...
    @property
    def msg_label(self) -> str: ...
    @property
    def delta_key(self) -> str: ...
    @property
    def is_error(self) -> bool: ...
    @property
    def is_spurious(self) -> bool: ...
    @property
    def error_label(self) -> str: ...
    def with_delta(self, delta: float | None) -> MieMessage: ...
    def to_dict(
        self,
        *,
        fields: Sequence[str] | None = None,
        standard_tick_rate_hz: float | None = None,
        year: int | None = None,
        utc_offset_minutes: int = 0,
    ) -> dict[str, Any]: ...
    def __replace__(self, **changes: Any) -> MieMessage: ...
    def __hash__(self) -> int: ...

@final
class RecordIterator(Iterator[MieMessage]):
    def __iter__(self) -> RecordIterator: ...
    def __next__(self) -> MieMessage: ...
    def close(self) -> None: ...

@final
class NativeReader:
    def __init__(
        self,
        path: str | PathLike[str],
        *,
        strict: bool,
        input_time_format: int,
        detect_records: int,
        lookahead_records: int,
        standard_tick_rate_hz: float | None,
        mux_enabled: bool,
        mux_delimiter: str,
        mux_field: int,
        calendar_year: int | None,
    ) -> None: ...
    @property
    def file_size(self) -> int: ...
    @property
    def sync_losses(self) -> int: ...
    @property
    def empty_recording(self) -> bool: ...
    def records(self) -> RecordIterator: ...

# Pipeline stages. Each takes any iterable of MieMessage -- a RecordIterator
# is taken over directly and left consumed -- and returns a RecordIterator.
def apply_filters(
    messages: Iterable[MieMessage],
    *,
    exclude_types: list[int],
    exclude_rts: list[int],
    exclude_buses: list[int],
    exclude_subaddresses: list[int],
    include_types: list[int],
    include_rts: list[int],
    include_buses: list[int],
    include_subaddresses: list[int],
) -> RecordIterator: ...
def order_rows(messages: Iterable[MieMessage], max_group: int) -> RecordIterator: ...

# CSV writer. `output` is a path (atomic file write) or a text stream; the
# result is (normal_count, error_count, partial), partial being
# (main_path, errors_path, offset, sync_losses).
_Outcome = tuple[int, int, tuple[Path, Path | None, int, int] | None]

def write_csv(
    messages: Iterable[MieMessage],
    output: str | PathLike[str] | TextIO,
    *,
    destination: str,
    input_path: str | PathLike[str] | None,
    no_clobber: bool,
    allow_partial: bool,
    time_format: int,
    year: int | None,
    utc_offset_minutes: int,
) -> _Outcome: ...
def write_csv_split(
    messages: Iterable[MieMessage],
    output: str | PathLike[str],
    *,
    input_path: str | PathLike[str] | None,
    no_clobber: bool,
    allow_partial: bool,
    time_format: int,
    year: int | None,
    utc_offset_minutes: int,
) -> _Outcome: ...
def csv_header() -> list[str]: ...
def message_to_row(
    msg: MieMessage, *, time_format: int, year: int | None, utc_offset_minutes: int
) -> list[str]: ...
def commit_targets(
    output: str | PathLike[str], split_errors: bool, allow_partial: bool
) -> list[Path]: ...
def paths_refer_to_same_file(
    input_path: str | PathLike[str], output_path: str | PathLike[str]
) -> bool: ...

# Multi-file merge (readers are the NativeReader behind each MieFileReader).
def merge_readers(
    readers: list[NativeReader],
    *,
    standard_tick_rate_hz: float | None,
    allow_partial: bool,
    strict: bool,
    collapse_duplicates: bool,
    collapse_window_us: int,
    max_collapse_survivors: int,
    delta_scope: int,
) -> RecordIterator: ...
def read_manifest(path: str | PathLike[str]) -> list[Path]: ...
def glob_match(pattern: str, name: str) -> bool: ...
def expand_glob(pattern: str) -> list[Path]: ...

# DELTA tracking. observe() returns
# (kind, seconds, prev_us, curr_us, key, first_for_key), kind a DeltaKind value.
def delta_key(rt: int, subaddress: int, transmit: bool) -> int: ...

@final
class DeltaTracker:
    def __init__(self, tick_rate_hz: float | None = None) -> None: ...
    def observe(
        self, command_word: CommandWord | None, timestamp: IrigTimestamp | StandardTimestamp
    ) -> tuple[int, float | None, int | None, int | None, int | None, bool]: ...

DEFAULT_DETECT_RECORDS: int
DEFAULT_LOOKAHEAD_RECORDS: int
DEFAULT_MUX_ENABLED: bool
DEFAULT_MUX_DELIMITER: str
DEFAULT_MUX_FIELD: int

def hex_dump_raw(path: Path, start_offset: int, length: int | None, stream: TextIO, /) -> None: ...
def hex_dump_records(
    path: Path, max_records: int | None, start_offset: int, stream: TextIO, /
) -> None: ...
def load_config(path: Path, /) -> dict[str, Any]: ...
def parse_utc_offset(text: str, /) -> int: ...
def log_level_threshold(name: str) -> int | None: ...
def set_irig_day_advisory(enabled: bool) -> None: ...
def irig_day_advisory() -> bool: ...
def table_fields() -> list[str]: ...
def columns(
    messages: Iterator[MieMessage],
    *,
    fields: Sequence[str] | None,
    standard_tick_rate_hz: float | None,
    year: int | None,
    utc_offset_minutes: int,
) -> dict[str, Any]: ...
